import './globals.css'
import { IBM_Plex_Mono } from 'next/font/google'

const OW_font = IBM_Plex_Mono({ weight:'400', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={OW_font.className}>
        {children}
      </body>
    </html>
  )
}
